### ISSUE TITLE
Old Dependencies

### ISSUE THREAD

**Issue by WhiffleFish** [4estlaine/TensorGames.jl#11]
How specific do the compat requirements need to be?

PATHSolver.jl recently released a version that allowed me to use this package with MacOS Silicon, but I wasn't actually able to use it because of the strict requirements that currently exist for this package.

Would it be worth it to allow non-breaking version changes for compatibility? Meaning we would change from this

```toml
[compat]
ChainRulesCore = "1.14"
ForwardDiff = "0.10.25"
PATHSolver = "1.1.1"
```

to this

```toml
[compat]
ChainRulesCore = "1"
ForwardDiff = "0.10"
PATHSolver = "1"
```
.

Also, CompatHelper seems to have stopped running.
